---
abstract: 'Object for handling URI templates'
author:
  - 'Brian Cassidy <bricas@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-Template
no_index:
  directory:
    - inc
    - t
requires:
  URI: 0
  URI::Escape: 0
  Unicode::Normalize: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.15
