--- 
abstract: Object for handling URI templates
author: Brian Cassidy <bricas@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: URI-Template
no_index: 
  directory: 
    - inc
    - t
requires: 
  Test::More: 0
  URI: 0
version: 0.09
